=== TheTellieTubbie/MetaCP_Project/AutoCrypto_metacp-artifact/meta-cp-FORMALISE/samples/meta-cp.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT model (sets*, customfunctions*,declarations*, protocol) >
    <!ATTLIST model version CDATA "0.1" >
    <!ELEMENT sets (set+) >
        <!ELEMENT set (set*) >
            <!ATTLIST set id ID #REQUIRED >
            <!ATTLIST set hint CDATA "" > <!-- this may be used as interpretation hint -->
            <!ATTLIST set tex CDATA "" >
            <!ATTLIST set description CDATA "" >
        <!ELEMENT function (argset+) >
            <!ATTLIST function id ID #REQUIRED >
            <!ATTLIST function arity CDATA "0" > <!-- default is constant -->
            <!ATTLIST function tex CDATA "" >
            <!ATTLIST function hint CDATA "" > <!-- this may be used as interpretation hint -->
            <!ATTLIST function notation (plain|infix|corner-ne|application) "plain" >
    <!ELEMENT argset (#PCDATA) >
        <!ATTLIST argset set IDREF #REQUIRED >
    <!ELEMENT customfunctions (function+) >
    <!ELEMENT customequations (equation+) >
    <!ELEMENT equation (#PCDATA) >
        <!ATTLIST equation id ID #REQUIRED >
    <!ELEMENT customrestrictions (restriction+) > 
        <!ELEMENT restriction (#PCDATA) >
            <!ATTLIST restriction id ID #REQUIRED >
    <!ELEMENT declarations (declaration*) >
      <!ELEMENT declaration (#PCDATA) >
          <!ATTLIST declaration variable ID #REQUIRED >
          <!ATTLIST declaration set IDREF #REQUIRED >
          <!ATTLIST declaration entity IDREF #REQUIRED >
          <!ATTLIST declaration label CDATA #IMPLIED >
          <!ATTLIST declaration tex CDATA #IMPLIED >
    <!ELEMENT protocol (description?, entity+, message+, finalise*, properties+) >
        <!ATTLIST protocol name CDATA "protocol" >
        <!ELEMENT description (#PCDATA) > <!-- CDATA encapsulation -->
        <!ELEMENT entity (knowledge?) >
            <!ATTLIST entity id ID #REQUIRED >
            <!ATTLIST entity name CDATA #REQUIRED >
            <!ATTLIST entity desc CDATA "party" >
            <!ELEMENT knowledge (variable+) >
                <!ATTLIST knowledge entity IDREF #REQUIRED >
        <!ELEMENT message (knowledge*, pre, event, channel, event, post, comment?) >
            <!ATTLIST message id ID #REQUIRED >
            <!ATTLIST message from IDREF #REQUIRED >
            <!ATTLIST message to IDREF #REQUIRED >
            <!ELEMENT channel (assignment*) >
              <!ATTLIST channel security (insecure|authenticated-sender|authenticated-recipient|secure) "insecure" >
            <!ELEMENT pre (assignment*) >
            <!ELEMENT event (variable*) >
              <!ATTLIST event type (send|receive) "send" >
            <!ELEMENT post (assignment*) >
            <!ELEMENT comment (#PCDATA) >
              <!ELEMENT assignment (((variable|application|tuple)|set?), comment?) >
                <!ATTLIST assignment variable IDREF #REQUIRED >
                <!ATTLIST assignment type (deterministic|probabilistic) "deterministic" >
              <!ELEMENT variable (#PCDATA) >
                <!ATTLIST variable id IDREF #REQUIRED >
                <!ATTLIST variable type (nonce|constant| entity| variable) "variable"  >
              <!ELEMENT application (application|argument)* >
                <!ATTLIST application function IDREF #REQUIRED >
                  <!ELEMENT argument (#PCDATA) >
                    <!ATTLIST argument id IDREF #REQUIRED >
                    <!ATTLIST argument type (nonce|constant| entity |variable) "variable" >
        <!ELEMENT finalise (knowledge?,assignment*) >
            <!ATTLIST finalise entity IDREF #REQUIRED >
            <!ATTLIST finalise lastmessage IDREF #REQUIRED >
        <!ELEMENT properties (securityparameter*, correctness?, authentication*, confidentiality*) >
            <!ELEMENT securityparameter (#PCDATA) >
                <!ATTLIST securityparameter id ID #REQUIRED >
            <!ELEMENT correctness (application+) >
            <!ELEMENT authentication (#PCDATA) >
                <!ATTLIST authentication integrity IDREF #REQUIRED >
                <!ATTLIST authentication towards IDREF #REQUIRED >
            <!ELEMENT confidentiality (secret+) >
                <!ELEMENT secret (allowed*) >
                    <!ATTLIST secret variable CDATA #REQUIRED >
                    <!ELEMENT allowed (#PCDATA) >
                        <!ATTLIST allowed entity IDREF #REQUIRED >
                        <!ATTLIST allowed atmessage IDREF "m-1" >

=== TheTellieTubbie/MetaCP_Project/AutoCrypto_metacp-artifact/meta-cp-FORMALISE/samples/naxos.xml
<!DOCTYPE model SYSTEM "../meta-cp.dtd">
<model version="0.1">
  <!-- Function provided by the builtin -->
  <builtin class="diffie-hellman">
    <function id="exp" arity="2" builtin="diffie-hellman"></function>
    <function id="g" builtin="diffie-hellman"></function>
  </builtin>
  <builtin class="symmetric-encryption">
    <function id="enc" arity="2" builtin="symmetric-encryption"></function>
    <function id="dec" arity="2" builtin="symmetric-encryption"></function>
  </builtin>
  <builtin class="asymmetric-encryption">
    <function id="aenc" arity="2" builtin="asymmetric-encryption"></function>
    <function id="adec" arity="2" builtin="asymmetric-encryption"></function>
  </builtin>
  <builtin class="hashing">
    <function id="hash" arity="1" builtin="hashing"></function>
  </builtin>
   <customfunctions>
    <function id="h1"></function> <!-- arity=1 -->
    <function id="h2"></function> <!-- arity=1 -->
  </customfunctions>

  <declarations>
    <declaration variable="kR"></declaration>
    <declaration variable="kI"></declaration>
    <declaration variable="exI"></declaration>
    <declaration variable="exR"></declaration>
    <declaration variable="hkI"></declaration>
    <declaration variable="hkR"></declaration>
    <declaration variable="pkI"></declaration>
    <declaration variable="pkR"></declaration>
    <declaration variable="pKexR"></declaration>
    <declaration variable="pKexI"></declaration>
    <declaration variable="hkIlkR"></declaration>
    <declaration variable="hkRlkI"></declaration>
    <declaration variable="hkIexR"></declaration>
    <declaration variable="hkRexI"></declaration>
  </declarations>

  <protocol name="Naxos Protocol">
    <entity id="I" name="I" desc="Initiator">
    </entity>
    <entity id="R" name="R" desc="Responded">
    </entity>

    <message id="m-1" from="I" to="R" channel="insecure">
      <rule id="r-1-sender">
        <pre>
          <fact id="eskI" name="eskI" type="fresh"><comment>exponent from N</comment></fact>
          <fact id="lkI" name="lkI" type="fresh"><comment>exponent from N</comment></fact>
          <assignment variable="exI">
            <application function="h1">
              <argument id="eskI" type="fresh"></argument>
              <argument id="lkI" type="fresh"></argument>
            </application>
          </assignment>
          <assignment variable="hkI">
            <application function="exp">
              <argument id="g" type="constant"></argument>
              <argument id="exI" ></argument>
            </application>
          </assignment>
          <assignment variable="pkI">
            <application function="exp">
              <argument id="g" type="constant"></argument>
              <argument id="lkI" type="fresh" ></argument>
            </application>
          </assignment>


        </pre>
        <event type="send">
          <variable id="hkI"></variable>
          <variable id="pkI"></variable>
        </event>
        <post>
        </post>
        <comment>send public key to other party</comment>
      </rule>
      
      <rule id="r-1-receiver">
        <pre></pre>
        <event type="receive">
          <variable id="hkI"></variable>
          <variable id="pkI"></variable>
        </event>
        <post></post>
      </rule>
    </message>

    <message id="m-2" from="R" to="I" channel="insecure">
      <knowledge entity="R">
        <variable id="hkI"></variable>
        <variable id="pkI"></variable>
      </knowledge>
      <knowledge entity="I">
        <variable id="eskI" type="fresh"></variable>
        <variable id="lkI"  type="fresh"></variable>
        <variable id="hkI"></variable>
        <variable id="pkI"></variable>
      </knowledge>
      <rule id="r-2-sender">
        <pre>
          <fact id="eskR" name="eskR" type="fresh"><comment>exponent from N</comment></fact>
          <fact id="lkR" name="lkR" type="fresh"><comment>exponent from N</comment></fact>
          
          <assignment variable="exR">
            <application function="h1">
              <argument id="eskR" type="fresh"></argument>
              <argument id="lkR" type="fresh"></argument>
            </application>
          </assignment>
          <assignment variable="hkR">
            <application function="exp">
              <argument id="g" type="constant"></argument>
              <argument id="exR" ></argument>
            </application>
          </assignment>

          <assignment variable="pKexR">
            <application function="exp">
              <argument id="pkI" ></argument>
              <argument id="exR" ></argument>
            </application>
          </assignment>
          <assignment variable="hkIlkR">
            <application function="exp">
              <argument id="hkI" ></argument>
              <argument id="lkR" type="fresh"></argument>
            </application>
          </assignment>
          <assignment variable="hkIexR">
            <application function="exp">
              <argument id="hkI" ></argument>
              <argument id="exR" ></argument>
            </application>

          </assignment>
          <assignment variable="kR">
            <application function="h2">
              <argument id="pKexR" ></argument>
              <argument id="hkIlkR" ></argument>
              <argument id="hkIexR" ></argument>
              <argument id="I" type="entity"></argument><!--type="identity"-->
              <argument id="R" type="entity"></argument><!--type="identity"-->
            </application>
          </assignment>

          <assignment variable="pkR">
            <application function="exp">
              <argument id="g" type="constant"></argument>
              <argument id="lkR" type="fresh" ></argument>
            </application>
          </assignment>

        </pre>
        <event type="send">
          <variable id="hkR"></variable>
          <variable id="pkR"></variable>
        </event>
        <post>
        </post>
        <comment>send public key to other party</comment>
      </rule>
      
      <rule id="r-2-receiver">
        <pre></pre>
        <event type="receive">
          <variable id="hkR"></variable>
          <variable id="pkR"></variable>
        </event>
        <post></post>
      </rule>
    </message>

    <message id="m-3" from="I" to="R" channel="insecure">
        <knowledge entity="I">
        <variable id="lkI" type="fresh"></variable>
        <variable id="pkI"></variable>
        <variable id="eskI"></variable>
        <variable id="hkI"></variable>
        <variable id="hkR"></variable>
        <variable id="pkR"></variable>
      </knowledge>
      
      <rule id="r-3-sender">
        <pre>
          <assignment variable="hkRlkI">
            <application function="exp">
              <argument id="hkR" ></argument>
              <argument id="lkI" type="fresh"></argument>
            </application>
          </assignment>
          <assignment variable="pKexI">
            <application function="exp">
              <argument id="pkR" ></argument>
              <argument id="exI" ></argument>
            </application>
          </assignment>
          <assignment variable="hkRexI">
            <application function="exp">
              <argument id="hkR" ></argument>
              <argument id="exI" ></argument>
            </application>


          </assignment>
          <assignment variable="kI">
            <application function="h2">
              <argument id="hkRlkI" ></argument>
              <argument id="pKexI" ></argument>
              <argument id="hkRexI" ></argument>
              <argument id="I" type="entity"></argument><!--type="identity"-->
              <argument id="R" type="entity"></argument><!--type="identity"-->
            </application>
          </assignment>
        </pre>
        <event type="compute">
            <argument id="kI" ></argument>
        </event>
        <post>
        </post>
        <comment>send public key to other party</comment>
      </rule>
      
      <!-- <rule id="r-1-receiver">
        <pre></pre>
        <event type="receive">
          <variable id="hkI"></variable>
          <variable id="pkI"></variable>
        </event>
        <post></post>
      </rule> -->
    </message>
    <properties>
          <authentication integrity="I" towards="R"></authentication>
          <authentication integrity="I" towards="R"></authentication>
          <confidentiality>
            <secret variable="kI">
              <allowed entity="I"></allowed>
              <allowed entity="R"></allowed>
            </secret>
          </confidentiality>
    </properties>
  </protocol>
</model>

=== TheTellieTubbie/MetaCP_Project/AutoCrypto_metacp-artifact/meta-cp-FORMALISE/samples/nsp.xml
<!DOCTYPE model SYSTEM "../meta-cp.dtd">
<model version="0.1">
  <!-- Function provided by the builtin -->
  <builtin class="diffie-hellman">
    <function id="exp" arity="2" builtin="diffie-hellman"></function>
    <function id="g" builtin="diffie-hellman"></function>
  </builtin>
  <builtin class="symmetric-encryption">
    <function id="enc" arity="2" builtin="symmetric-encryption"></function>
    <function id="dec" arity="2" builtin="symmetric-encryption"></function>
  </builtin>
  <builtin class="asymmetric-encryption">
    <function id="aenc" arity="2" builtin="asymmetric-encryption"></function>
    <function id="adec" arity="2" builtin="asymmetric-encryption"></function>
    <function id="keygen" arity="0" builtin="asymmetric-encryption"></function>
    <function id="publicKey" arity="1" builtin="asymmetric-encryption"></function>
    <function id="privateKey" arity="1" builtin="asymmetric-encryption"></function>
  </builtin>
  <builtin class="hashing">
    <function id="hash" arity="1" builtin="hashing"></function>
  </builtin>
  <builtin class="pairing">
    <function id="tuple" arity="n" builtin="pairing"></function>
    
  </builtin>
  
  <declarations>
    <declaration variable="one" entity="I"></declaration>  
    <declaration variable="two" entity="R"></declaration>  
    <declaration variable="three" entity="I"></declaration>  
    <declaration variable="m1" entity="I"></declaration>  
    <declaration variable="m2" entity="R"></declaration>  
    <declaration variable="m3" entity="I"></declaration>  
    <declaration variable="kI" entity="I"></declaration>  
    <declaration variable="kR" entity="R"></declaration>  
    <declaration variable="skI" entity="I"></declaration>  
    <declaration variable="skR" entity="R"></declaration>  
    <declaration variable="pkI" entity="I"></declaration>  
    <declaration variable="pkR" entity="R"></declaration>  
  </declarations>
  
  <protocol name="Needham Schroeder Protocol">
    <description>Authenticating Two Parties</description>
    
    <entity id="I" name="I" desc="Initiator">
      <knowledge entity="I">
         <assignment variable="kI">
            <application function="keyGenerator">
            </application>
          </assignment>
         <assignment variable="skI">
            <application function="privateKey">
              <argument id="kI"></argument>
            </application>
         </assignment>
         <assignment variable="pkI">
           <application function="publicKey">
                <argument id="kI"></argument>
            </application>
          </assignment>
          <variable id="pkR"></variable>
      </knowledge>
    </entity>
    <entity id="R" name="R" desc="Responder">
      <knowledge entity="R">
         <assignment variable="kR">
            <application function="keyGenerator">
            </application>
          </assignment>
         <assignment variable="skR">
            <application function="privateKey">
                <argument id="kR"></argument>
            </application>
        </assignment>
         <assignment variable="pkR">
           <application function="publicKey">
                <argument id="kR"></argument>
            </application>
          </assignment>
          <variable id="pkI"></variable>
      </knowledge>
    </entity>
    <message id="m-1" from="I" to="R" channel="insecure">
      <knowledge entity="I">
        <variable id="skI"></variable>
        <variable id="pkI"></variable>
        <variable id="pkR"></variable>
      </knowledge>
      <knowledge entity="R">
        <variable id="skR"></variable>
        <variable id="pkR"></variable>
        <variable id="pkI"></variable>
      </knowledge>
      <rule id="r-1-sender">
        <pre>
         <fact id="ni" name="ni" type="fresh"><comment>exponent from N</comment></fact>
         <assignment variable="m1">
            <application function="aenc">
                <application function="tuple">
                    <argument id="one" type="constant"></argument>
                    <argument id="ni" type="fresh"></argument>
                    <argument id="I" type ="entity"></argument>
                </application>
              <argument id="pkR"></argument>
            </application>
          </assignment>
        </pre>
        <event type="send">
          <variable id="m1"></variable>
        </event>
        <post>

        </post>
        <comment>send public key to other party</comment>
      </rule>
      <rule id="r-1-receiver">
        <pre>
        </pre>
        <event type="receive">
          <variable id="m1"></variable>
        </event>
        <post></post>
      </rule>
    </message>
    
    <message id="m-2" from="R" to="I" channel="insecure">
      <knowledge entity="I">
        <variable id="skI"></variable>
        <variable id="pkI"></variable>
        <variable id="pkR"></variable>
        <variable id="ni"></variable>
        <variable id="m1"></variable>
      </knowledge>
      <knowledge entity="R">
        <variable id="skR"></variable>
        <variable id="pkR"></variable>
        <variable id="pkI"></variable>
        <variable id="m1"></variable>
      </knowledge>
      <rule id="r-2-sender">
        <pre>
          <fact id="nr" name="nr" type="fresh"><comment>exponent from N</comment></fact>
           <assignment variable="ni">
            <application function="fst">
              <application function="snd">
                <application function="adec">
                  <argument id="m1"></argument>  
                  <argument id="skR"></argument>
                </application>
              </application>
             </application>
          </assignment> 
          <assignment variable="m2">
              <application function="aenc">
                  <application function="tuple">
                      <argument id="two" type="constant"></argument>
                      <argument id="ni"></argument>
                      <argument id="nr" type="fresh"></argument>
                  </application>
                <argument id="pkI"></argument>
              </application>
            </assignment>
        </pre>
        <event type="send">
          <variable id="m2"></variable>
        </event>
        <post>
        </post>
        <comment>send public key to other party</comment>
      </rule>
      <rule id="r-2-receiver">
        <pre>
          
        </pre>
        <event type="receive">
          <variable id="m2"></variable>
        </event>
        <post></post>
      </rule>
    </message>
    <message id="m-3" from="I" to="R" channel="insecure">
      <knowledge entity="I">
        <variable id="skI"></variable>
        <variable id="pkI"></variable>
        <variable id="pkR"></variable>
        <variable id="ni"></variable>
        <variable id="m1"></variable>
        <variable id="m2"></variable>
      </knowledge>
      <knowledge entity="R">
        <variable id="skR"></variable>
        <variable id="pkR"></variable>
        <variable id="pkI"></variable>
        <variable id="m1"></variable>
        <variable id="nr"></variable>
        <variable id="ni"></variable>
        <variable id="m2"></variable>
      </knowledge>
      <rule id="r-3-sender">
        <pre>
          <assignment variable="nr">
            <application function="fst">
              <application function="snd">
                <application function="adec">
                  <argument id="m2"></argument>  
                  <argument id="skI"></argument>
                </application>
              </application>
             </application>
          </assignment> 
          <assignment variable="m3">
             <application function="aenc">
                 <application function="tuple">
                     <argument id="three" type="constant"></argument>
                     <argument id="nr"></argument>
                 </application>
               <argument id="pkR"></argument>
             </application>
          </assignment>
        </pre>
        <event type="send">
          <variable id="m3"></variable>
        </event>
        <post>
        </post>
        <comment>send public key to other party</comment>
      </rule>
      <rule id="r-3-receiver">
        <pre>
        </pre>
        <event type="receive">
          <variable id="m3"></variable>
        </event>
        <post></post>
      </rule>
    </message>
    
    <finalise entity="I" lastmessage="m-2">
    </finalise>
    
    <finalise entity="R" lastmessage="m-2">
    </finalise>
    
    <properties>
      <authentication integrity="I" towards="R"></authentication>
      <authentication integrity="R" towards="I"></authentication>
    </properties>
  </protocol>
</model>

=== TheTellieTubbie/MetaCP_Project/AutoCrypto_metacp-artifact/meta-cp-FORMALISE/samples/dh.xml
<!DOCTYPE model SYSTEM "../meta-cp.dtd">
<model version="0.1">  
    <sets>
        <set id="N" tex="\mathbb{N}" description="Natural numbers"></set>
        <set id="Zp" tex="\mathbb{Z}_p" description="Integers modulo p"></set>
    </sets>
  
    <customfunctions>
        <function id="exp" arity="2" notation="corner-ne" hint="group-exponentiation">
            <argset set="Zp"></argset>
            <argset set="N"></argset>
            <argset set="Zp"></argset>
        </function>
        <function id="g" hint="group-exponentiation">
            <argset set="Zp"></argset>
        </function>
        <function id="p">
            <argset set="N"></argset>
        </function>
        <function id="eq" arity="2" tex="=" notation="infix" hint="equality">
            <argset set="Zp"></argset>
            <argset set="Zp"></argset>
        </function>
    </customfunctions>
  
    <declarations>
        <declaration variable="x"  entity="A" set="N"></declaration>
        <declaration variable="y"  entity="B" set="N"></declaration>
        <declaration variable="kA" entity="A" set="Zp" tex="k_A" label="k"></declaration>
        <declaration variable="kB" entity="B" set="Zp" tex="k_B" label="k"></declaration>
        <declaration variable="gx" entity="A" set="Zp" tex="X"></declaration>
        <declaration variable="gy" entity="B" set="Zp" tex="Y"></declaration>
    </declarations>
  
    <protocol name="Diffie-Hellman key exchange">
        <description>Exchange a long term secret key</description>
    
        <entity id="A" name="A" desc="Alice">
        </entity>
        <entity id="B" name="B" desc="Bob">
        </entity>
    
        <message id="m-1" from="A" to="B">
            <knowledge entity="A">
                <variable id="g" type="constant"></variable>
            </knowledge>
            <knowledge entity="B">
                <variable id="g" type="constant"></variable>
            </knowledge>
            <pre>
                <assignment variable="x" type="probabilistic"></assignment>
                <assignment variable="gx">
                    <application function="exp">
                        <argument id="g" type="constant"></argument>
                        <argument id="x" type="nonce"></argument>
                    </application>
                </assignment>
            </pre>
            <event type="send">
                <variable id="gx"></variable>
            </event>
            <channel security="insecure"></channel>
            <event type="receive">
                <variable id="gx"></variable>
            </event>
            <post></post>
            <comment>send public key to other party</comment>
        </message>
    
        <message id="m-2" from="B" to="A">
            <knowledge entity="A">
                <variable id="g" type="constant"></variable>
                <variable id="x" type="nonce"></variable>
                <variable id="gx"></variable>
            </knowledge>
            <knowledge entity="B">
                <variable id="g" type="constant"></variable>
                <variable id="gx"></variable>
            </knowledge>
            <pre>
                <assignment variable="y" type="probabilistic"></assignment>
                <assignment variable="gy">
                    <application function="exp">
                        <argument id="g" type="constant"></argument>
                        <argument id="y" type="nonce"></argument>
                    </application>
                </assignment>
            </pre>
            <event type="send">
                <variable id="gy"></variable>
            </event>
            <channel security="insecure"></channel>
            <event type="receive">
                <variable id="gy"></variable>
            </event>
            <post></post>
            <comment>send public key to other party</comment>
        </message>
    
        <finalise entity="A" lastmessage="m-2">
            <assignment variable="kA">
                <application function="exp">
                    <argument id="gy"></argument>
                    <argument id="x" type="nonce"></argument>
                </application>
            </assignment>
        </finalise>
    
        <finalise entity="B" lastmessage="m-2">
            <assignment variable="kB">
                <application function="exp">
                    <argument id="gx"></argument>
                    <argument id="y" type="nonce"></argument>
                </application>
            </assignment>
        </finalise>
    
        <properties>
            <securityparameter id="n">512</securityparameter>
            <correctness>
                <application function="eq">
                    <argument id="kA"></argument>
                    <argument id="kB"></argument>
                </application>
            </correctness>
            <authentication integrity="A" towards="B"></authentication>
            <authentication integrity="B" towards="A"></authentication>
            <confidentiality>
                <secret variable="k">
                    <allowed entity="A"></allowed>
                    <allowed entity="B"></allowed>
                </secret>
            </confidentiality>
        </properties>
    </protocol>
</model>
